### ISSUE TITLE
Modify IM server from a different node

### ISSUE THREAD

**Issue by danepowell** [ros-visualization/interactive_markers#10]
Let's say you launch a standard interactive marker server in one node, and you'd like to be able to edit it (add / remove markers and menu entries) from a second node. Is this currently possible? I'm pretty sure the answer is no.

Here's my motivation- I'm writing a node that interfaces with a haptic device, the Phantom Omni (just imagine a 3D mouse), and uses it to control interactive markers: https://github.com/danepowell/omni_im

In the existing omni_im demo, I launch the IM server and Omni callback from within the same node. In the real world, however, I'll be integrating with an existing interactive marker setup, such as the PR2 Interactive Manipulation demo.

Thus, I'd like to be able to run my omni_im node and have it 'latch into' an existing interactive marker server, and insert a menu entry on each marker to allow the user to select it for Omni control.

Do you have any suggestions on how to solve this problem?

**Comment by danepowell** [comment]
I guess what I'm really requesting is for IM servers to implement a service-based API that allows external nodes to access / modify / control the server.

**Comment by dgossow** [comment]
Considering that you don't have control over the other node's internal logic and when it changes Interactive Markers and their menus, this doesn't sound plausible. Maintaining a consistent shared state between server and client without introducing race conditions is hard enough.
Instead, you should write something that hooks into the Interactive Marker client - i.e. RViz - and so doesn't require any modifications in the server. See Adam Leeper's work for a reference - https://github.com/aleeper/interaction_cursor_3d. The interaction cursor stuff uses the Razer Hydra, but he did some work with the Omni as well.

**Comment by danepowell** [comment]
Thanks for the quick feedback. I'm just trying to grok Adam's code, so correct me if I'm wrong- it seems that he basically implements an Rviz display plugin that takes the 3d mouse's position, gets the 'active control', and sends the position and orientation of the 3d mouse to that control using the InteractiveMarkerControl::handle3DCursorEvent() method. Obviously there's lots of housekeeping stuff around that, but is that the gist of it?

FWIW, I managed to work around this issue in my current [server-based implementation](https://github.com/danepowell/omni_im) by watching the interactive marker feedback topic and simply latching onto the most-recently touched marker. That's much easier than having users click on a menu option. But, the server-based implementation has two major problems: it doesn't respect the constraints of the marker controls (i.e. only moving on-axis), and it's very slow to update, I think since there's some delay in the server reading the feedback topic and actually applying the updated position.

**Comment by dgossow** [comment]
As to Adam's stuff, that's basically it, but you would have to ask him.

You could support constraints in your implementation by checking which control was clicked and what it's interaction_mode is. How fast the server updates the pose mainly depends on how the server node is implemented, but there can be some latency because of the network transmission.

**Comment by danepowell** [comment]
Thanks a lot for your feedback! The client-side implementation sounds like a much better solution.

**Comment by dgossow** [comment]
No problem, it's always welcome if people build cool stuff with Interactive Markers. :sunglasses: Good luck with your project & let me know when there's a finished package or paper coming out of this.
