### ISSUE TITLE
Generalized twist_marker_server node

### ISSUE THREAD

**Issue by mikepurvis** [ros-visualization/interactive_markers#11]
There are a large number of twist-based robots out there which could benefit from a general marker server with basic forward/back/side-to-side/rotate controls.

At Clearpath, we have Husky, Kingfisher, and Grizzly, but there is also Turtlebot, and many others which have either no markers support, or a bespoke one that is essentially a ripoff of [turtlebot_interactive_markers](https://github.com/turtlebot/turtlebot_viz/blob/hydro-devel/turtlebot_interactive_markers/src/turtlebot_marker_server.cpp). My suggestion is for a `twist_marker_server` node to live in the interactive_markers package, providing baseline functionality to basic differential drive and holonomic drive bases.

Suggested parameters for such a common node would be:
- link_name (default: /base_link)
- linear_scale (default: 1.0)
- angular_scale (default: 1.0)
- holonomic (default: False)

Holonomic set to true would enable a linear_y controller, for drive bases with that capability.

If you'd be interested to merge this and release to Hydro, I can provide a pull request in fairly short order. (The alternative is creating new kingfisher_interactive_markers and grizzly_interactive_markers packages, so I'm motivated!)

**Comment by dgossow** [comment]
Great idea, I wouldn't put this into the interactive_markers package though but call it something like interactive_twist_marker or interactive_marker_teleop or so.

**Comment by mikepurvis** [comment]
I was wondering about that—what's the rationale to not just include it with the library, though? I don't believe it adds any dependencies, and it would be logical to include as "example" code.

**Comment by dgossow** [comment]
You could include this as example code into the interactive_marker_tutorials, but if this is supposed to be referenced in robot-specific launchfiles / tutorials and stuff, that's not a good location. interactive_markers should only contain the library, no apps.

**Comment by mikepurvis** [comment]
@tfoote, what's your opinion on a package name which would work for Turtlebot, perhaps to switch to for indigo? My inclination would be toward `robot_interactive_markers`, with a node called `twist_server`, and room left for other reusable robot-agnostic marker nodes. But I'm easy-going—would just like to choose something which will work well outside of the CPR platforms.

@dirk-thomas Would there be room for such a package in the ros-visualization org?

**Comment by dgossow** [comment]
This would be a nice place for generic head-pointer and cartesian controller interactive marker nodes.

**Comment by dirk-thomas** [comment]
@mikepurvis I am not sure what the package/repo would be about. In your previous comment it sounds more like the functionality you describe is a node containing a marker server.

`ros-visualization` contains stuff which has a user interface - mostly Qt. So a generic rqt plugin to use the server node would be a good match for that org unit. The server node itself probably not that good.

**Comment by mikepurvis** [comment]
@dirk-thomas Yes, the idea would be a robot-agnostic version of what is currently almost exact cut/paste duplication in turtlebot_interactive_markers, husky_interactive_markers, etc., with the goal that other twist-based platforms where the maintainer has not yet bothered to create such a copy-package might gain marker support with the addition of just a launchfile, rather than the bigger commitment which comes with another package.

If not this org, can you recommend somewhere more appropriate where it might find a home? I can also just put it on the clearpathrobotics org, but I feel like it's more likely to get traction on one of the official ros-\* ones. If not ros-visualization, why are interactive_markers and interactive_marker_proxy located here?

**Comment by dirk-thomas** [comment]
Well, you have to ask @dgossow that question :smile: Anyway it makes sense to keep your proposed package in the same org unit as `interactive_markers` since it is tighly connected to it. Please propose a repo name and let me know which GitHub users should have access to it then I will create the repo.

**Comment by mikepurvis** [comment]
Okay, cool. Will wait on @tfoote's input re: repo/package name.

**Comment by tfoote** [comment]
I think keeping it in ros-visualization org is good as it is closely connected to the interactive markers.  I'd make it it 's own repo with the package and repo named.  interactive_marker_twist_server  It's long but very clear. The node name could be shortened to twist_server or twist_marker_server.

**Comment by mikepurvis** [comment]
Aight— @dirk-thomas, if you could create me ros-visualization/interactive_marker_twist_server. When it comes time to release, is it okay to just use clearpath-gbp? If not, please also create ros-gbp/interactive_marker_twist_server-release.

In terms of users, just me for now, though obviously @dgossow and @tfoote if they're interested.

**Comment by dirk-thomas** [comment]
I created https://github.com/ros-visualization/interactive_marker_twist_server as well as https://github.com/ros-gbp/interactive_marker_twist_server-release. Yuo got admin access to both of them - David and Tully are already in the owner team of these org units.

**Comment by mikepurvis** [comment]
Perfect, thanks. Will be on this in the next week or two.

On Thu, Oct 17, 2013 at 1:12 PM, Dirk Thomas notifications@github.comwrote:

> I created
> https://github.com/ros-visualization/interactive_marker_twist_server as
> well as https://github.com/ros-gbp/interactive_marker_twist_server-release.
> Yuo got admin access to both of them - David and Tully are already in the
> owner team of these org units.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ros-visualization/interactive_markers/issues/11#issuecomment-26528408
> .

## 

http://uwmike.com

**Comment by mikepurvis** [comment]
Okay, initial release has been cut of [interactive_marker_twist_server](http://wiki.ros.org/interactive_marker_twist_server). We're using it as part of the Grizzly's [view_robot.launch](https://github.com/g/grizzly_desktop/blob/hydro-devel/grizzly_viz/launch/view_robot.launch). 

That resolves this ticket.
