### ISSUE TITLE
Python API MenuHandler insert function

### ISSUE THREAD

**Issue by ndutoit** [ros-visualization/interactive_markers#14]
Hello,

There seems to be a change in the MenuHandler insert function:
Before (line 64):
if parent != None:

Now (line 65):
if parent is None:

I believe that the older version is correct, but can you please verify, and if so, update the repository?

Thank you,
Noel

**Comment by wjwwood** [comment]
Yes, thank you for catching that, I'll put a new release out right now, but it won't make it to public debs for a few days.

Sorry for the regression.

**Comment by wjwwood** [comment]
New hydro release is in the pipeline: https://github.com/ros/rosdistro/pull/3008
