### ISSUE TITLE
InteractiveMarker Feedback has Timestamp 0

### ISSUE THREAD

**Issue by orzechow** [ros-visualization/interactive_markers#17]
I have an InteractiveMarker (Arrow) and use its Timestamp `header.stamp` for further processing.
Since indigo it is constantly set to 0 (both `sec` & `nsec`)
In groovy (I could check on hydro soon) the timestamp is updating well.

Moved this issue from https://github.com/ros-visualization/rviz/issues/792

**Comment by dgossow** [comment]
This is probably a problem in rviz.

**Comment by dgossow** [comment]
Wait, which timestamp do you mean? What you get in the feedback or something else?

**Comment by wjwwood** [comment]
I'm going to close this since there hasn't been any updates. @orzechow feel free to comment here if you find time. I can always reopen the issue.

**Comment by pbeeson** [comment]
We are seeing a similar issue in Kinetic, where IMs that work fine, but will report a timestamp of 0 after a setPose() call to the IM server with a pose that uses a different frame from the frame used in the original insert() call to set up the marker.  If you then setPose() back to the original frame used when creating the marker, the timestamps start being non-zero again.  Seems related to this issue, as the user may have been calling setPose() early on with maybe a different frame from what was used during IM creation.  I can create a new issue if desired.

**Comment by dgossow** [comment]
Could you provide some code that triggers this behaviour?

**Comment by pbeeson** [comment]
Not really easy because its a complicated piece of code that this is embedded in.  By the time I write a standalone, anyone should do it by modifying a tutorial, so I'll leave those instructions and move on for the day because this has already cost us a lot of time to track down and we have a demo to get running.

1) Make an IM client that sets up an IM by calling insert() with some frame (e.g. "left_hand"). Something that isn't a fixed frame in the URDF.
2) Make a processFeedback callback for the IM that prints out the feedback header.  
3) make some event (let's say right button up) in the processFeedback that calls setPose() on the IM with the Rviz Fixed Frame (e.g. "/world")
4) Notice that the header stamp is now 0.

There are some related issues we've seen with non-"world" frames, but I won't bring those up now.

**Comment by pbeeson** [comment]
Actually, let me mention the related issues.  So, if you set up an IM with let's saw frame "left_palm", you can call setPose() on it all day with poses in the left_palm frame and it works fine.  If you then call setPose() but if a pose and the current Rviz Fixed Frame, the IM still works correctly but the feedback header timestamp is 0.  If you call setPose() with any frame other than "left_palm" or the Rviz Fixed Frame then the IM goes "crazy" and the processFeedback always shows the Rviz Fixed Frame value (e.g. "/world") in the header that's returned regardless of the frame that was sent.  It's like anytime the frame does not match the startup frame it assumes it must be in the the Fixed Frame, which leads to very weird behavior.  The way we are going to get around this is to get the IM, delete it, then readd it in whatever frame we want to change to, but it seems like that is overkill given the setPose() should be able to handle that.  If not, then that needs to be better documented.

**Comment by pbeeson** [comment]
I'm starting to this Fix Frame issue may be an issue in the RViz side of IMs, but I would think the header stamp getting set to 0 might still be IM server side?  I haven't done a deep dig into the code on either side.

**Comment by pbeeson** [comment]
Yep.  It looks to be on the Rviz side.  Looks like when the creation frame is used it all works right.  When its not the creation from it assumed the RViz Fix frame and sets the timestamp to 0.

```
 if ( frame_locked_ )
  {
    // frame-locked IMs will return their pose in the same coordinate frame
    // as they were set up with (the "reference frame").
    // The transformation's timestamp will be the one used for placing
    // the reference frame into the fixed frame
    feedback.header.frame_id = reference_frame_;
    feedback.header.stamp = reference_time_;
.
.
.
.
.
}
  }
  else
  {
    // Timestamped IMs will return feedback in RViz's fixed frame
    feedback.header.frame_id = context_->getFixedFrame().toStdString();
    // This should be ros::Time::now(), but then the computer running
    // RViz has to be time-synced with the server
    feedback.header.stamp = ros::Time();
```

**Comment by dgossow** [comment]
I vaguely remember that I wrote those lines of code, but not in detail all the considerations that went into it. It does seem that this behavior is intentional though. What would the correct behavior be in your opinion?

**Comment by pbeeson** [comment]
In my opinion, the time stamp shouldn't be 0, it should be
ros::Time::now().  I'm unsure why it matters that rviz is time synced with
the IM server, I can't see an instance where you would have RViz and IMs
running on different machines since IMs are inherently grounded in Rviz
itself.

**Comment by dgossow** [comment]
In a typical scenario, the IM server runs on the robot while RViz runs on a remote machine. This is not an issue when only viewing stuff in RViz, but when RViz sends feedback the different time domains on the two machines start to matter.

Perhaps a way to solve this would be to assign Time::now() inside the IM server before passing feedback on via a callback. Of course this is slightly intrusive and could as well be done in the user code, so perhaps the current behavior should just be better documented?
