### ISSUE TITLE
setPose SEGFAULTs if called before applyChanges

### ISSUE THREAD

**Issue by mkoval** [ros-visualization/interactive_markers#18]
Calling `setPose()` on an interactive marker causes a SEGFAULT if `applyChanges()` was not called on the server at least once since the marker was created. I traced the actual SEGFAULT to [the doSetPose function](https://github.com/ros-visualization/interactive_markers/blob/hydro-devel/src/interactive_marker_server.cpp#L463). The value of `header` [passed from `setPose()`](https://github.com/ros-visualization/interactive_markers/blob/hydro-devel/src/interactive_marker_server.cpp#L231) is invalid because, in this case, `marker_context_it = marker_contexts_.end()`.

I'm not exactly sure what's going on here, so I wasn't able to come up with a fix that worked. I tried passing the new `header` to `doSetPose` if `marker_contexts_` does not contain `name`, but this caused nothing to render in RViz.

This is a serious problem for certain use cases of the interactive marker API. I have a lot of superfluous bookkeeping in my code just to work around this issue.

**Comment by wjwwood** [comment]
Thanks for the report, I'm not sure when I'll have time to track down this error, but if you learn anymore yourself please let us know. In the mean time perhaps some of the other interactive marker users can take a quick glance? @dgossow @hersh @aleeper
