### ISSUE TITLE
Python Interactive Marker Server does not clear markers

### ISSUE THREAD

**Issue by calderpg** [ros-visualization/interactive_markers#3]
The clear() function in interactive_marker_server.py in class InteractiveMarkerServer does not actually clear the markers from Rviz as the comparable C++ API does. The clear() function should add the following lines to clear the server:

``` python
for marker_name in self.marker_contexts.keys():
    self.erase(marker_name)
self.applyChanges()
```

**Comment by dgossow** [comment]
Thanks for reporting. 

applyChanges() will not be called explicitly, since you might want to do that later, e.g. to avoid flickering.

``` python
for marker_name in self.marker_contexts.keys():
    self.erase(marker_name)
```
