### ISSUE TITLE
Release please?

### ISSUE THREAD

**Issue by mikepurvis** [ros-visualization/interactive_markers#31]
Am particularly interested in getting #26 released.

**Comment by wjwwood** [comment]
Sorry it took so long:
- Indigo:
  - https://github.com/ros/rosdistro/pull/12488
- Jade:
  - https://github.com/ros/rosdistro/pull/12490
- Kinetic:
  - https://github.com/ros/rosdistro/pull/12491

We're going to hold these release pr's (and all others) until we can do a build farm restart and maybe a sync of one or two of the ros distros. But at least the releases are in the pipe now.
