### ISSUE TITLE
Marker contains invalid quaternions (length not equal to 1)!

### ISSUE THREAD

**Issue by NickoDema** [ros-visualization/interactive_markers#35]
ROS Kinetic | Ubuntu 16.04
I have some problem with markers visualization. When I used indigo everything was fine. But after migration to kinetic, every marker which uses TF return "Marker contains invalid quaternions (length not equal to 1)!" in corresponding r-viz field.
Can I get some help with it?

Thanks for your time.

![screenshot from 2018-01-04 20-31-08](https://user-images.githubusercontent.com/14163708/34576283-6b8471d0-f18e-11e7-914f-be7e6efb4191.png)

**Comment by dhood** [comment]
@Ram2301 there's been a break in behaviour with the latest rviz release in kinetic/lunar. The tutorials will be updated to use normalised quaternions, as should other quaternion publishers. In the next rviz release invalid quaternions will still be displayed but with a warning.

**Comment by NickoDema** [comment]
@dhood  ok, I'll just use normalised quaternions for now. Thank you.
