### ISSUE TITLE
Interactive marker doesn't display non-ascii characters as name

### ISSUE THREAD

**Issue by juanluishortelano** [ros-visualization/interactive_markers#40]
When setting a non-ascii character ('ñ' 'æ' ,'ü', etc) as the marker's name rviz will show a blank space.

For example, when naming the marker "Rænör" the following visualization appears:

![Screenshot_20190509_114439](https://user-images.githubusercontent.com/14986892/57444239-eca91e80-724f-11e9-99ff-4ed177b3e6d7.png)

**Comment by dgossow** [comment]
Interesting. Did you use unicode characters?

This sounds like it would be pretty hard to support with the current code base.

**Comment by rhaschke** [comment]
I filed a PR for rviz to solve this issue. However, it's not trivial to decide about the supported codepoint range in advance.

**Comment by rhaschke** [comment]
Fixed in rviz.
