### ISSUE TITLE
[ros2] lots of linter related CI failures on nightly

### ISSUE THREAD

**Issue by wjwwood** [ros-visualization/interactive_markers#59]
See: https://ci.ros2.org/view/nightly/job/nightly_linux_release/1440/testReport/

**Comment by dirk-thomas** [comment]
Introduced in https://github.com/ros-visualization/interactive_markers/pull/58/files#diff-4b7f911bc8d771577f78770a335653e8R3

**Comment by wjwwood** [comment]
CI on Linux up to `interactive_markers`:

[![Build Status](https://ci.ros2.org/job/ci_linux/9296/badge/icon)](https://ci.ros2.org/job/ci_linux/9296/)
