### ISSUE TITLE
Release interactive_markers to Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-visualization/interactive_markers#65]
Would you mind releasing `interactive_markers` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 103 repos need it.

I'm not sure how much work it will need. At a minimum it needs #64.

@wjwwood ping :)

**Comment by seanyen** [comment]
cc @tfoote @dgossow

**Comment by sloretz** [comment]
@wjwwood friendly ping :)

**Comment by ahcorde** [comment]
this PR is also relevant https://github.com/ros-visualization/interactive_markers/pull/67

**Comment by wjwwood** [comment]
I'm probably not going to get to this in the coming week given the Foxy deadline.

**Comment by rhaschke** [comment]
I can prepare a release over the weekend. Testing the package in a Noetic environment right now.

**Comment by rhaschke** [comment]
@ahcorde, before preparing a new release for Noetic, I would like to migrate to tf2.
I prepared a corresponding PR: #68.

**Comment by sloretz** [comment]
Friendly ping @wjwwood @rhaschke . How's the `interactive_markers` Noetic work going? Would a source entry in rosdistro enabling PR jobs be useful?

**Comment by wjwwood** [comment]
I won't have anytime until the Foxy API is frozen. Likely after this week.

**Comment by rhaschke** [comment]
Done: https://github.com/ros/rosdistro/pull/24601
