### ISSUE TITLE
[ROS 2] Flaky tests in Eloquent

### ISSUE THREAD

**Issue by azeey** [ros-visualization/interactive_markers#74]
There are a couple of flaky tests that seem to occur only in Eloquent:

*  [TestInteractiveMarkerClient](http://build.ros2.org/view/Eci/job/Eci__nightly-fastrtps_ubuntu_bionic_amd64/353/testReport/junit/interactive_markers/TestInteractiveMarkerClient/feedback/)
   *  [History](http://build.ros2.org/job/Eci__nightly-debug_ubuntu_bionic_amd64/354/testReport/interactive_markers/TestInteractiveMarkerClient/history/)
   * Output:
    ```
    /tmp/ws/src/ros-visualization/interactive_markers/test/interactive_markers/test_interactive_marker_client.cpp:376
    Expected equality of these values:
      mock_server->feedback_received_
        Which is: 0
      1u
        Which is: 1

    /tmp/ws/src/ros-visualization/interactive_markers/test/interactive_markers/test_interactive_marker_client.cpp:380
    Expected equality of these values:
      mock_server->feedback_received_
        Which is: 1
      2u
        Which is: 2
    ```

* [TestInteractiveMarkerServerWithMarkers](http://build.ros2.org/job/Eci__nightly-debug_ubuntu_bionic_amd64/348/testReport/junit/interactive_markers/TestInteractiveMarkerServerWithMarkers/update_communication/)
   * [History](http://build.ros2.org/job/Eci__nightly-debug_ubuntu_bionic_amd64/354/testReport/interactive_markers/TestInteractiveMarkerServerWithMarkers/history/)
   * Output:
    ```
    /tmp/ws/src/ros-visualization/interactive_markers/test/interactive_markers/test_interactive_marker_server.cpp:339
    Expected equality of these values:
      mock_client_->updates_received
        Which is: 0
      1u
        Which is: 1

    /tmp/ws/src/ros-visualization/interactive_markers/test/interactive_markers/test_interactive_marker_server.cpp:340
    Expected: (mock_client_->last_update_message) != (nullptr), actual: 16-byte object <00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00> vs (nullptr)
    ```

**Comment by jacobperron** [comment]
Since Eloquent is EOL, and presumably this was only happening in Eloquent, I'm inclined to close this ticket.
