### ISSUE TITLE
Can't select "arrow" with Qt 5.12 & Ogre 1.10.12

### ISSUE THREAD

**Issue by wolfv** [ros-visualization/interactive_markers#76]
Hi, I am wondering if I am doing something stupidly wrong. I have a conda build of RViz that works quite nicely. The only remaining problem seems to be that I can't select / drag interactive markers. They do render correctly though.
It seems like the mouse interaction with the marker just doesn't work. Does someone know where to look in order to fix / debug this?

![Screenshot from 2020-07-21 20-51-59](https://user-images.githubusercontent.com/885054/88095019-bf1a6d80-cb94-11ea-9a34-01e9b2387a42.png)

![Screenshot from 2020-07-21 20-52-14](https://user-images.githubusercontent.com/885054/88095025-c17cc780-cb94-11ea-8fac-3681f60d6880.png)

**Comment by wolfv** [comment]
![Screenshot from 2020-07-21 20-58-31](https://user-images.githubusercontent.com/885054/88095172-f7ba4700-cb94-11ea-8cb1-1bc32250fc32.png)

In moveit, the interactive marker didn't work either. Any ideas appreciated!

**Comment by rhaschke** [comment]
Hi @wolfv, I suggest to first observe the communication on the interactive marker topics. Do you see messages there?
Does the standard release work as expected? What is different w.r.t. a "conda build"? These are just some ideas. Cannot help more in the next two weeks.

**Comment by wolfv** [comment]
Thanks for the reply! No communication can be seen on the feedback, update and update_full topic (using the simple_marker, single interactive marker example).
The RVIZ debug image shows me different colors when hovering over the different elements.

The difference is that the conda build doesn't use system dependencies, but instead gets the deps from conda-forge (in this case). For example, the OGRE package: https://anaconda.org/conda-forge/ogre

I don't have access to the standard release as I am on Fedora right now, but I guess it will work as expected. I'll try to debug this further...
The part of the interactive marker that draw the arrow & handle the mouse interaction are in RViz or in this repo?

**Comment by wolfv** [comment]
I have debugged a little further and it seems that this line in `interaction_tool.cpp` returns an empty result:

```
  // Pick exactly 1 pixel
  context_->getSelectionManager()->pick(event.viewport, event.x, event.y, event.x + 1, event.y + 1,
                                        results, true);
```

... will debug further tomorrow.

**Comment by wolfv** [comment]
when i check the color values that are used in colorToHandle, I can see different values but it seems to be the grid lines and sometimes a spurious value... not what I would expect. Do you think the textures could be messed up? Maybe I should publish a full render of the click buffer to a image topic?

**Comment by wolfv** [comment]
OK I just checked and with RViz 1.13.9 it was working fine so I believe this might be a regression with the latest RViz. Specifically this commit looks like it could be responsible: https://github.com/ros-visualization/rviz/commit/e5ef587b50079e71cce929e4f2d3b380c030b0d7#diff-a671220daaa00b9dfc6ad2ed4972d385

Will try to debug this further, hope you don't mind me writing this down.

**Comment by wolfv** [comment]
Fixed in rviz now
