### ISSUE TITLE
Get all markers from server

### ISSUE THREAD

**Issue by ommmid** [ros-visualization/interactive_markers#93]
Currently there is no public function member to get all markers from the server. However, one alternative way is to subscribe to `/<node_name>/update_full` topic to get a list of markers name and then do a `server->get(name)` to have access to them which seem to be redundant. A function that can return all the markers would be easier and more useful.

**Comment by jacobperron** [comment]
Based on your description, I think you are referring to the ROS 1 implementation, though there isn't a method to get all markers in the ROS 2 implementation either. 

Please consider opening a pull request adding the feature :slightly_smiling_face:

**Comment by ommmid** [comment]
Here is the PR related to this issue: #94
